sonar.projectKey=ankitsahu6387_HireConnectApp
sonar.organization=ankitsahu6387
sonar.projectName=hire-connect-frontend

sonar.sources=src

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/*.spec.ts,src/main.ts,src/environments/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/main.ts,src/environments/**,src/app/app.config.ts,src/app/app.routes.ts,src/app/guards/**,src/app/interceptors/**,src/app/components/**,src/app/pages/**,src/app/services/analytics.service.ts,src/app/services/application.service.ts,src/app/services/interview.service.ts,src/app/services/job.service.ts,src/app/services/notification.service.ts,src/app/services/payment.service.ts,src/app/services/user.service.ts

sonar.sourceEncoding=UTF-8
